fix(radio-button): adding checkmark inside radio for redesign
coveo/react-vapor pull request #1844
Opened 2021-01-27 18:46 UTC by kdang-coveo

### Proposed Changes
Fixing radio button to look like mockup design:

**Mockup**
![image](https://user-images.githubusercontent.com/66333175/106036717-adfe6c00-60a3-11eb-80ac-12801b5ed1e4.png)

![image](https://user-images.githubusercontent.com/66333175/106036736-b2c32000-60a3-11eb-83b0-2106a71738d0.png)

- Added checkmark svg in Radio button and adjusted alignment

**Implementation Results:**

![image](https://user-images.githubusercontent.com/66333175/106038459-f9197e80-60a5-11eb-8147-5f9cd9265da2.png)
![image](https://user-images.githubusercontent.com/66333175/106038484-ff0f5f80-60a5-11eb-92a6-eea7830a21fd.png)

### Potential Breaking Changes

### Acceptance Criteria

-   [ ] The proposed changes are covered by unit tests
-   [ ] The potential breaking changes are clearly identified
-   [ ] [README.md](https://github.com/coveo/react-vapor/blob/master/README.md) is adjusted to reflect the proposed changes (if relevant)

2021-01-28 11:58 UTC, aiheon approved these changes

2021-01-28 11:58 UTC, aiheon commented on packages/vapor/scss/controls/radios.scss
>                  background-color: #1372ec; // digital-blue-60
this here can be changed to use the variable :+1:

2021-01-28 11:58 UTC, aiheon commented on packages/vapor/scss/controls/radios.scss
> +                    border: 2px solid #e5e8e8;
here too I think :thinking:

2021-01-28 15:32 UTC, j-mcgregor approved these changes

2021-01-28 16:40 UTC, rosalie-liu approved these changes

2021-01-28 16:57 UTC, guscoveo requested changes
Hi Kien, thanks for improving the alignment of the radio button! I fixed it in the library as well. There are some minor tweaks to add though. Please do slack me to let me know if ever it isn't clear 🙏 

![image](https://user-images.githubusercontent.com/77753668/106171709-e06d9f00-615f-11eb-8146-07ca12f71400.png)

2021-01-28 21:37 UTC, rosalie-liu commented on packages/vapor/scss/controls/radios.scss
> +            font-weight: 400;
```suggestion
            font-weight: var(--main-font-bold);
```

2021-01-28 21:39 UTC, rosalie-liu commented on packages/vapor/scss/controls/radios.scss
> +                    border: 2px solid #e5e8e8;
```suggestion
                    border: 2px solid var(--grey-40);
```

2021-01-28 21:51 UTC, kdang-coveo commented
> Hi Kien, thanks for improving the alignment of the radio button! I fixed it in the library as well. There are some minor tweaks to add though. Please do slack me to let me know if ever it isn't clear 🙏
> 
> ![image](https://user-images.githubusercontent.com/77753668/106171709-e06d9f00-615f-11eb-8146-07ca12f71400.png)

- [x] Corrected Radio button Border colour
- [x] Font weight 400 & 500 applied with var
- [x] Colour checkmark fixed to correct colour
- [ ] Transition effect - slightly left due to padding - will explore a different svg or reposition

2021-01-29 14:30 UTC, aiheon commented
@kdang-coveo  the transition effect you talk about, is it the label moving up and down because of the font weight changing? :thinking:  maybe the padding is not big enough in the demo xD 
![image](https://user-images.githubusercontent.com/63734941/106287117-719e4d80-6214-11eb-96cb-41520c9388e8.png)

2021-01-29 16:57 UTC, kdang-coveo commented
> @kdang-coveo the transition effect you talk about, is it the label moving up and down because of the font weight changing? 🤔 maybe the padding is not big enough in the demo xD
> ![image](https://user-images.githubusercontent.com/63734941/106287117-719e4d80-6214-11eb-96cb-41520c9388e8.png)

The transition effect mentioned by @guscoveo, was when it was expanding while checked, it expanded slightly to the left and out. I believe it was a padding issue but P.O resolved this issue with his commit 👍 

![radio-transition](https://user-images.githubusercontent.com/66333175/106304074-e5e2ec00-6228-11eb-98f4-980fee12f26f.gif)

2021-02-02 14:27 UTC, guscoveo approved these changes

2021-02-02 19:58 UTC, kdang-coveo commented
New transition effect:
![radio transition fixed](https://user-images.githubusercontent.com/66333175/106655261-20b98c80-6567-11eb-997a-726abffdc2b2.gif)

2021-02-02 19:58 UTC, merged