chore(svg): adding svg for dataset trials
coveo/react-vapor pull request #2142
Opened 2021-09-30 12:48 UTC by kdang-coveo

### Proposed Changes

[ADUI-7572](https://coveord.atlassian.net/browse/ADUI-7572)

### Potential Breaking Changes

Adding the required svg for the sample data sets and updated the push-source svg to the new one as per AnneCath

### Acceptance Criteria

-   [ ] The proposed changes are covered by unit tests
-   [ ] The potential breaking changes are clearly identified
-   [ ] [README.md](https://github.com/coveo/react-vapor/blob/master/README.md) is adjusted to reflect the proposed changes (if relevant)

2021-09-30 13:19 UTC, toofff commented on packages/vapor/resources/icons/svg/arrow-right-link.svg
> +
remove this line

2021-09-30 13:19 UTC, toofff commented on packages/vapor/resources/icons/svg/catalog-source-sm.svg
> +
remove this line

2021-09-30 13:19 UTC, toofff commented on packages/vapor/resources/icons/svg/ecommerce-yellow.svg
> +
remove this line

2021-09-30 13:19 UTC, toofff commented on packages/vapor/resources/icons/svg/explore-sample-dataset.svg
> +
remove this line

2021-09-30 13:19 UTC, toofff commented on packages/vapor/resources/icons/svg/push-source-sm.svg
> +
remove this line

2021-09-30 13:19 UTC, toofff commented on packages/vapor/resources/icons/svg/sitemap-source-sm.svg
> +
remove this line

2021-09-30 13:19 UTC, toofff commented on packages/vapor/resources/icons/svg/web-source-sm.svg
> +
remove this line

2021-09-30 13:19 UTC, toofff commented on packages/vapor/resources/icons/svg/website-search-green.svg
> +
remove this line

2021-09-30 13:19 UTC, toofff commented on packages/vapor/resources/icons/svg/youtube-source-sm.svg
> +
remove this line

2021-09-30 13:19 UTC, toofff commented on packages/vapor/resources/icons/svg/arrow-right-link.svg
> +<svg fill="none" height="16" viewBox="0 0 16 16" width="16" xmlns="http://www.w3.org/2000/svg"><g stroke="#1372ec" stroke-linecap="round" stroke-linejoin="round"><path d="m1.5 8h12"/><path d="m10.5 4
```suggestion
<svg viewBox="0 0 16 16" stroke="#1372ec" stroke-linecap="round" stroke-linejoin="round" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="m1.5 8h12"/><path d="m10.5 4.5 4 3.5-4 3.5"/></svg>
```

2021-09-30 13:19 UTC, toofff commented on packages/vapor/resources/icons/svg/arrow-right-link.svg
> +<svg fill="none" height="16" viewBox="0 0 16 16" width="16" xmlns="http://www.w3.org/2000/svg"><g stroke="#1372ec" stroke-linecap="round" stroke-linejoin="round"><path d="m1.5 8h12"/><path d="m10.5 4
And the color should don't blue but `stroke="#282829"`

ping @acverrette ?

2021-09-30 13:19 UTC, toofff commented on packages/vapor/resources/icons/svg/catalog-source-sm.svg
> +<svg fill="none" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><mask id="a" fill="#fff"><ellipse fill="#fff" rx=".901048" ry
Remove attribute `height` & `width` please

2021-09-30 13:19 UTC, toofff commented on packages/vapor/resources/icons/svg/ecommerce-yellow.svg
> +<svg fill="none" height="40" viewBox="0 0 40 40" width="40" xmlns="http://www.w3.org/2000/svg"><path d="m0 8c0-4.41828 3.58172-8 8-8h24c4.4183 0 8 3.58172 8 8v24c0 4.4183-3.5817 8-8 8h-24c-4.41828 0-
Remove attribute `height` & `width` please

2021-09-30 13:19 UTC, toofff commented on packages/vapor/resources/icons/svg/explore-sample-dataset.svg
> +<svg fill="none" height="40" viewBox="0 0 40 40" width="40" xmlns="http://www.w3.org/2000/svg"><path d="m0 8c0-4.41828 3.58172-8 8-8h24c4.4183 0 8 3.58172 8 8v24c0 4.4183-3.5817 8-8 8h-24c-4.41828 0-
Remove attribute `height` & `width` please

2021-09-30 13:19 UTC, toofff commented on packages/vapor/resources/icons/svg/index-website.svg
> +<svg fill="none" height="40" viewBox="0 0 40 40" width="40" xmlns="http://www.w3.org/2000/svg"><path d="m0 8c0-4.41828 3.58172-8 8-8h24c4.4183 0 8 3.58172 8 8v24c0 4.4183-3.5817 8-8 8h-24c-4.41828 0-
Remove attribute `height` & `width` please

2021-09-30 13:19 UTC, toofff commented on packages/vapor/resources/icons/svg/push-source-sm.svg
> +<svg fill="none" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><path d="m0 3c0-1.65685 1.34315-3 3-3h18c1.6569 0 3 1.34315 3 3v18c0 1.6569-1.3431 3-3 3h-18c-1.65685 0-
Remove attribute `height` & `width` please

2021-09-30 13:19 UTC, toofff commented on packages/vapor/resources/icons/svg/sitemap-source-sm.svg
> +<svg fill="none" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><path d="m0 3c0-1.65685 1.34315-3 3-3h18c1.6569 0 3 1.34315 3 3v18c0 1.6569-1.3431 3-3 3h-18c-1.65685 0-
Remove attribute `height` & `width` please

2021-09-30 13:19 UTC, toofff commented on packages/vapor/resources/icons/svg/source-push.svg
> +<svg fill="none" height="40" viewBox="0 0 40 40" width="40" xmlns="http://www.w3.org/2000/svg"><path d="m0 8c0-4.41828 3.58172-8 8-8h24c4.4183 0 8 3.58172 8 8v24c0 4.4183-3.5817 8-8 8h-24c-4.41828 0-
Remove attribute `height` & `width` please

2021-09-30 13:19 UTC, toofff commented on packages/vapor/resources/icons/svg/web-source-sm.svg
> +<svg fill="none" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><path d="m0 3c0-1.65685 1.34315-3 3-3h18c1.6569 0 3 1.34315 3 3v18c0 1.6569-1.3431 3-3 3h-18c-1.65685 0-
Remove attribute `height` & `width` please

2021-09-30 13:19 UTC, toofff commented on packages/vapor/resources/icons/svg/website-search-green.svg
> +<svg fill="none" height="40" viewBox="0 0 40 40" width="40" xmlns="http://www.w3.org/2000/svg"><path d="m0 8c0-4.41828 3.58172-8 8-8h24c4.4183 0 8 3.58172 8 8v24c0 4.4183-3.5817 8-8 8h-24c-4.41828 0-
Remove attribute `height` & `width` please

2021-09-30 13:19 UTC, toofff commented on packages/vapor/resources/icons/svg/youtube-source-sm.svg
> +<svg fill="none" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><path d="m12.0802 5.625h.0345l.0856.00075c1.014.00487 5.5852.04988 6.8497.44925.75.15 1.35.825 1.575 1.5
Remove attribute `height` & `width` please

2021-09-30 14:45 UTC, gdostie requested changes

2021-09-30 18:12 UTC, gdostie approved these changes

2021-10-01 17:43 UTC, aiheon approved these changes

2021-10-01 17:52 UTC, merged